### ISSUE TITLE
g++ compile error

### ISSUE THREAD

**Issue by sam025023** [NCAR/bspline#2]
Hi There,
I try to test the bspline algorithm from this project. 
I tested with visual studio 2013, it works. 
Now I try to compline it with g++ (g++ (GCC) 6.1.1 20160501)  in linux OS. It did compile. 
 Please help. Appreciate it very much.
Sam

Hereby the error msg from the compiler.
**> 
**> g++ -c -Wall -march=armv7-a -O2 -DNDEBUG -MMD -I Src -I Src/bspline Src/bspline/BSplineLib.cpp -o obj/Src/bspline/BSplineLib.o
> mkdir -p obj/Src/bspline/
> g++ -c -Wall -march=armv7-a -O2 -DNDEBUG -MMD -I Src -I Src/bspline  Src/bspline/BSpline.cpp -o obj/Src/bspline/BSpline.o
> Src/bspline/BSpline.cpp: In member function 'bool BSpline<T>::solve(const T*)':
> Src/bspline/BSpline.cpp:110:18: error: 'my' has not been declared
>          for (m = my::max(0, mx-1); m <= my::min(mx+2, M); ++m) {
>                   ^~
> Src/bspline/BSpline.cpp:110:41: error: 'my' has not been declared
>          for (m = my::max(0, mx-1); m <= my::min(mx+2, M); ++m) {
>                                          ^~****

**Comment by burghart** [comment]
Hi,

The file BSpline.cpp will not compile on its own, as you see in the failed
compilation. Rather, BSplineLib.cpp, which includes both BSpline.cpp and
BSplineBase.cpp, is the only file intended to be compiled directly.

I hope this helps you.  Good luck!

Chris
